--Outdated




local UIS = game:GetService("UserInputService")
mod = {
AmbushAlways = "Again & Again & Again", -- Againx3
AmbushFaster = "Afterimage", --Afterimage
AmbushMore ="Back For Seconds", --BackSeconds
Chaos1 ="Uh Oh", -- Uh Oh
Chaos2 = "How Unfortunate", -- How Unfortunate
Chaos3 = "Chaos, Chaos", -- Chaos, Chaos
DupeMore = "Wrong Number", -- Wrong Number
DupeMost = "Battle of Wits", -- Battle of Wits
EntitiesLess = "Good Time",
EntitiesMore = "Bad Time",
EntitiesMost = "Really Bad Time",
EntitiesMoster = "Worst Time Ever",
EyesFour = "Four Eyes",
EyesMore = "Nosey",
EyesMost = "Always Watching",
EyesTwice = "Seeing Double",
FigureFaster = "Come Back Here",
Fog = "Bad Ventilation",
GoldSpawnLess = "El Goblino Was Here",
GoldSpawnMore = "El Goblino On Break",
GoldSpawnNone = "El Goblino's Pay Day",
HideTime = "Rent's Due",
ItemDurabilityLess = "Wear and Tear",
ItemSpawnLess = "Less Stuff",
ItemSpawnMore = "More Stuff",
ItemSpawnNone = "Out of Stuff",
Jammin = "Jammin",
LeastHidingSpots = "Nowhere to Hide",
LightsLeast = "Power Shortage", -- Power Shortage
LightsLess = "Bad Electrical Work", -- Bad Electrical Work
LightsMore = "Lights On", -- Lights On
LightsNeverFlicker = "Electrical Work", -- Electrical Work
LightsOut = "Lights Out", --Lights Out
LockMore = "Locked and Loaded", --Locked and Loaded
LockMost = "Key Key Key Key", --Keyx4
NoGuidingLight = "Gone Fishing", -- Gone Fishing
NoKeySound = "SoundProofing", -- Soundproofing
PlayerCrouchSlow = "My Knees are Killing Me", --Knees Hurt
PlayerDamageMore = "Last Few Breaths", -- Last Few Breaths
PlayerDamagesMost = "Last Breath", --Last Breath
PlayerFast = "Didn't Skip Leg Day", -- No Skip Leg Day
PlayerFaster = "Faster, Faster, Faster", -- Fasterx3
PlayerFastest = "MAXIMUM OVERDRIVE", -- MAXIMUM OVERDRIVE
PlayerHealthLeast = "Tripped and Fell", -- Tripped and Fell
PlayerHealthLess = "Tripped", --Tripped
PlayerSlow = "My Legs are Killing Me", --My Legs Are Killing Me
PlayerSlowHealth = "Injuries", --Injuries
Rooms = "Room For More", -- Room For More
RoomsA90 = "Stop Right There",  --Stop Right There
RushFaster = "I'm Runnin' Here", --Im Runnin' Here
RushMore = "Rush Hour", --Manggarai Rush Hour
RushQuiet = "I'm Tip-Toein' Here", -- TIPPY TOE RUSHY ROE
ScreechFast = "Think Fast", -- Think Fast Chucklenuts
ScreechFaster = "Think Faster", -- Think Faster
ScreechLight = "I'm Everywhere", -- Im EVerywhere
SeekFaster = "It Can Run Too", -- It Can Run Too
Slippery = "Wet Floor", -- Pain Wet Floor
SnareMore = "Watch Your Step", -- Watch Your Step
SnareMost = "Are Those Pancakes?!", -- Are Those Pancakes?!
SnareMoster = "I Love Pancakes!!!", -- I Love Pancakes!!!
SuperHardMode = "Super Hard Mode",
Template = "Template",
TimothyLess =  "Bug Spray", --Bug Spray
TimothyMore = "Itchy", -- Itchy
Voicelines = "Voice Acting" -- dum da dum da dum da dum dum da paw paw pew pawww
}

--LINE--

modcol = {
AmbushAlways = Color3.fromRGB(171, 241, 194), -- Againx3
AmbushFaster = Color3.fromRGB(171, 241, 194), --Afterimage
AmbushMore =   Color3.fromRGB(171, 241, 194), --BackSeconds
Chaos1 = Color3.fromRGB(255, 115, 134), -- Uh Oh
Chaos2 = Color3.fromRGB(255, 86, 111), -- How Unfortunate
Chaos3 = Color3.fromRGB(255, 75, 78), -- Chaos, Chaos
DupeMore = Color3.fromRGB(255, 160, 184), -- Wrong Number
DupeMost = Color3.fromRGB(255, 160, 184), -- Battle of Wits
EntitiesLess = Color3.fromRGB(249, 255, 184),
EntitiesMore = Color3.fromRGB(255, 146, 148),
EntitiesMost = Color3.fromRGB(255, 115, 134),
EntitiesMoster = Color3.fromRGB(255, 39, 43),
EyesFour = Color3.fromRGB(199, 188, 255),
EyesMore = Color3.fromRGB(199, 188, 255),
EyesMost = Color3.fromRGB(199, 188, 255),
EyesTwice = Color3.fromRGB(199, 188, 255),
FigureFaster = Color3.fromRGB(235, 132, 114),
Fog = Color3.fromRGB(255, 160, 147),
GoldSpawnLess = Color3.fromRGB(255, 160, 147),
GoldSpawnMore = Color3.fromRGB(192, 255, 169),
GoldSpawnNone = Color3.fromRGB(255, 146, 148),
HideTime = Color3.fromRGB(255, 160, 143),
ItemDurabilityLess = Color3.fromRGB(255, 160, 147),
ItemSpawnLess = Color3.fromRGB(255, 160, 147),
ItemSpawnMore = Color3.fromRGB(192, 255, 169),
ItemSpawnNone = Color3.fromRGB(255, 115, 134),
Jammin = Color3.fromRGB(255, 146, 148),
LeastHidingSpots = Color3.fromRGB(255, 146, 148),
LightsLeast = Color3.fromRGB(255, 146, 148), -- Power Shortage
LightsLess = Color3.fromRGB(255, 160, 147), -- Bad Electrical Work
LightsMore = Color3.fromRGB(249, 255, 184), -- Lights On
LightsNeverFlicker = Color3.fromRGB(255, 187, 147), -- Electrical Work
LightsOut = Color3.fromRGB(255, 115, 134), --Lights Out
LockMore = Color3.fromRGB(255, 146, 148), --Locked and Loaded
LockMost = Color3.fromRGB(255, 115, 134), --Keyx4
NoGuidingLight = Color3.fromRGB(255, 187, 147), -- Gone Fishing
NoKeySound = Color3.fromRGB(255, 187, 147), -- Soundproofing
PlayerCrouchSlow = Color3.fromRGB(255, 187, 147), --Knees Hurt
PlayerDamageMore = Color3.fromRGB(255, 115, 134), -- Last Few Breaths
PlayerDamagesMost = Color3.fromRGB(255, 86, 111), --Last Breath
PlayerFast = Color3.fromRGB(249, 255, 184), -- No Skip Leg Day
PlayerFaster = Color3.fromRGB(192, 255, 169), -- Fasterx3
PlayerFastest = Color3.fromRGB(170, 230, 255), -- MAXIMUM OVERDRIVE
PlayerHealthLeast = Color3.fromRGB(255, 146, 148), -- Tripped and Fell
PlayerHealthLess = Color3.fromRGB(255, 160, 147), --Tripped
PlayerSlow = Color3.fromRGB(255, 160, 147), --My Legs Are Killing Me
PlayerSlowHealth = Color3.fromRGB(255, 160, 147), --Injuries
Rooms = Color3.fromRGB(255, 220, 79), -- Room For More
RoomsA90 = Color3.fromRGB(255, 220, 79),  --Stop Right There
RushFaster = Color3.fromRGB(191, 187, 212), --Im Runnin' Here
RushMore = Color3.fromRGB(191, 187, 212), --Manggarai Rush Hour
RushQuiet = Color3.fromRGB(191, 187, 212), -- TIPPY TOE RUSHY ROE
ScreechFast = Color3.fromRGB(189, 196, 211), -- Think Fast Chucklenuts
ScreechFaster = Color3.fromRGB(189, 196, 211), -- Think Faster
ScreechLight = Color3.fromRGB(189, 196, 211), -- Im EVerywhere
SeekFaster = Color3.fromRGB(255, 108, 108), -- It Can Run Too
Slippery = Color3.fromRGB(255, 160, 147), -- Pain Wet Floor
SnareMore = Color3.fromRGB(165, 179, 113), -- Watch Your Step
SnareMost = Color3.fromRGB(165, 179, 113), -- Are Those Pancakes?!
SnareMoster = Color3.fromRGB(165, 179, 113), -- I Love Pancakes!!!
SuperHardMode = Color3.fromRGB(255, 134, 217),
Template = Color3.fromRGB(109, 113, 141),
TimothyLess =  Color3.fromRGB(157, 179, 148), --Bug Spray
TimothyMore = Color3.fromRGB(157, 179, 148), -- Itchy
Voicelines = Color3.fromRGB(255, 255, 255) -- dum da dum da dum da dum dum da (x3) dum da dum da dum da dum dum paw paw pew pawww
}
--list is alphabetical
