local function findToolType(b) -- , b is idk!!
for i,v in pairs(workspace:GetDescendants()) do
if v.Name == b and v:IsA("Tool") then
if v:FindFirstChild"ClickDetector" ~= nil then
prtname = v
print(v.Name)
end
end
end
end
local function findToolTypebyPart(b) -- WHat is?
for i,v in pairs(workspace:GetDescendants()) do
if v.Name == b then
if v:FindFirstChild"ClickDetector" ~= nil then
prtname = v
print(v.Name)
end
end
end
end
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("guops GUI", "GrapeTheme")
local Tab = Window:NewTab("Tools and teams")
local Tab2 = Window:NewTab("player")
local Stuff = Window:NewTab("Problems and credits")

local Section = Tab:NewSection("Tools")

Section:NewButton("Loop hit", "Loops hit", function()
-- Script generated by SimpleSpy - credits to exx#9394
local Player = Game.Players.LocalPlayer
local Mouse = Player:GetMouse()
while true do wait()
--Mouse.Button1Down:Connect(function()
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Stomp"
}

game:GetService("Players").LocalPlayer.Character.Fight.FightScript.FightEvent:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Kick"
}

game:GetService("Players").LocalPlayer.Character.Fight.FightScript.FightEvent:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Slap"
}

game:GetService("Players").LocalPlayer.Character.Fight.FightScript.FightEvent:FireServer(unpack(args))

end


end)
Section:NewButton("Get Money Once", "collects some money", function()
for i,v in pairs(workspace:GetDescendants()) do
if v.Name == "Bundle" then
GuiText = v.Parent.CashGui.TextLabel
if not GuiText.Text:match("Available") then
bd = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = v.CFrame
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = bd
end
end
end
end)
Section:NewToggle("AutoFarm money", "Gets some money if this is toggled on", function(state)
if state then
autofarm(true)

print"toggled on"
    else
autofarm(false)
print"Dude, the toggle is off!"

end
end)
function autofarm(stateStatus)
while true do 
wait(1)
if stateStatus == true then
for i,v in pairs(workspace:GetDescendants()) do
if v.Name == "Bundle" then
GuiText = v.Parent.CashGui.TextLabel
if not GuiText.Text:match("Available") then
bd = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
wait()
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = v.CFrame
wait()
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = bd

print("Toggle is on")
end
end
end


elseif stateStatus == false then
end
end
end
